[workspace]
resolver = "2"
members = [
    "crates/bili2text",
    "crates/bili-client",
    "crates/asr",
    "crates/downloader",
]

[workspace.package]
version = "0.2.1"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trtyr/bili2text"

[workspace.dependencies]
bili-client = { path = "crates/bili-client", version = "0.2.0" }

[profile.release]
lto = "thin"
